<x-guest-layout>
    <div class="container w-full px-5 py-6 mx-auto">
        <h1 class="text-4xl text-center py-6">
            Terms and conditions
        </h1>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet, urna in suscipit dapibus, purus nulla rhoncus odio, sed vestibulum odio sapien vel massa. Nulla sodales ac urna a finibus. Nunc dignissim erat nec velit convallis, in vehicula mauris euismod. Nullam rhoncus posuere leo, vel maximus sapien venenatis in. Fusce ipsum velit, iaculis at vestibulum consectetur, vulputate et nisi. Vivamus congue efficitur lacinia. Maecenas dictum, orci vel pulvinar cursus, metus nisi malesuada lacus, nec feugiat leo nunc eu lectus. Maecenas varius quis lorem vitae consequat. Morbi et justo metus.

            Integer eu sollicitudin quam. Nam dapibus lorem vitae lorem consectetur, non pharetra nisi tincidunt. Maecenas interdum ante sed mi dapibus sollicitudin. Mauris hendrerit vitae risus vel ullamcorper. Phasellus vel vulputate sem. Donec ornare nisi lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean rhoncus augue at fermentum commodo. Morbi tristique tincidunt augue, vel cursus nibh mattis sed. Nam vel diam quis ex sodales dignissim. Nulla quis quam a mauris vehicula mattis nec id lorem. Phasellus tellus metus, pretium id vulputate quis, fermentum id magna. Nam id dapibus nibh. Donec ut tellus a orci interdum fringilla sed at augue. Proin iaculis enim vel tincidunt tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

            Etiam eu dui vel lorem placerat finibus. Integer dignissim elementum dui, ac consectetur nunc tincidunt id. Vestibulum a magna tempus, porttitor mi vel, ultrices felis. Fusce in ex in urna ullamcorper congue. Donec mollis pretium elementum. In nec quam hendrerit, malesuada urna non, mattis dolor. Mauris tristique quam non nunc tristique, quis cursus urna rutrum. Aenean egestas euismod sem vitae tincidunt. Donec accumsan, leo at auctor eleifend, est odio tempor ipsum, vel vulputate tellus augue nec diam. Cras ultricies, orci in tempor viverra, est nisl eleifend erat, in viverra leo quam mollis nunc. Fusce vitae nisi quis nunc pellentesque lobortis vel a dolor.

            Quisque eu arcu venenatis est auctor viverra eget sit amet dolor. Sed tincidunt dui ac mauris viverra, et tincidunt quam iaculis. Proin nulla erat, lacinia ac gravida eu, luctus ac ipsum. Vestibulum ornare, arcu a laoreet egestas, leo dui dictum ante, sed efficitur nisi sapien ac mi. Suspendisse posuere nunc sit amet sem consectetur gravida ut eget mi. Suspendisse potenti. Aliquam vel arcu scelerisque neque commodo fermentum. Fusce tincidunt, libero ac euismod molestie, turpis ipsum euismod velit, vitae luctus lacus justo sit amet dolor. Phasellus aliquam risus sit amet porttitor pellentesque. Praesent non nulla gravida, accumsan leo et, tempor arcu. Suspendisse sollicitudin purus sit amet est blandit, sit amet euismod leo dignissim. Vestibulum in nulla purus.

            Pellentesque interdum eros metus, id facilisis tellus vulputate ut. Nulla justo tortor, maximus eget ex viverra, iaculis venenatis augue. Nulla scelerisque rhoncus libero eget consectetur. Aliquam facilisis mollis mauris, vitae viverra libero tincidunt vel. Ut lacinia commodo mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod ante metus, ut ultrices metus placerat condimentum.

            Maecenas leo urna, malesuada sed interdum quis, commodo vel mauris. Aliquam a aliquet tortor. Duis eu erat vitae enim aliquet aliquam. Aenean nec consequat risus. Praesent elementum, erat vel facilisis scelerisque, tortor magna sodales lorem, quis fermentum lacus lacus in velit. Donec mattis ligula ex, ac commodo sapien ultrices at. Nunc viverra nisl sed neque porta posuere. Nulla facilisi. Donec et sagittis massa, quis elementum libero.

            Praesent eget dolor commodo, maximus justo ac, vestibulum nunc. Maecenas rutrum tellus vehicula consectetur rhoncus. Donec rutrum rhoncus diam, eu sollicitudin felis ultrices vitae. Suspendisse posuere orci rhoncus condimentum imperdiet. Praesent leo velit, egestas ut lacinia vel, malesuada sit amet mauris. Sed mauris est, tincidunt sed feugiat quis, ullamcorper in velit. Curabitur eu sapien sed purus dapibus imperdiet. Quisque suscipit nunc lorem, id hendrerit est scelerisque id. Pellentesque a purus faucibus, vestibulum odio ultricies, viverra arcu. Etiam dictum enim quis pellentesque pulvinar. Mauris aliquam justo ligula, quis vestibulum quam ornare eu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque feugiat tincidunt velit sit amet mattis. Aenean eu orci rhoncus, tempor massa a, ultricies sapien. Cras euismod libero nisl, sed mattis justo tempor in. Pellentesque egestas sapien ut ex iaculis, at eleifend ligula convallis.

            Donec lorem nisl, tempor ac diam non, faucibus blandit nunc. Ut molestie elit vel tempus sagittis. Fusce sollicitudin fermentum sapien, facilisis iaculis augue rhoncus a. Donec neque ipsum, egestas eu fringilla finibus, faucibus quis nibh. Nunc ut lectus orci. Praesent ullamcorper orci vitae porta sagittis. Etiam luctus nisi ut purus dignissim egestas. Donec id maximus arcu. Nullam tristique tellus a metus vulputate, vel venenatis mauris viverra. Maecenas molestie tristique interdum. Vestibulum viverra nisl ut nibh tristique, sit amet condimentum augue lacinia. Cras luctus dui id lectus hendrerit tincidunt.

            In porta lacus cursus nulla fringilla efficitur sit amet ac purus. Phasellus fermentum nec lectus eu commodo. Curabitur posuere massa ut ex iaculis ultricies. Sed placerat ornare nunc, in pellentesque justo pharetra sit amet. Aenean vitae ex ante. Ut tortor nulla, aliquet vitae quam in, ultrices elementum erat. Mauris pellentesque eget sem non porta. Vestibulum imperdiet feugiat congue. Quisque viverra euismod ultricies. Fusce congue pharetra nibh eget mollis. Pellentesque nec lacinia lacus, nec maximus nibh. Nam iaculis, orci in faucibus ultrices, ante tortor aliquam lectus, sit amet aliquet ante magna porttitor purus. Quisque nec sem sollicitudin, venenatis odio ac, dictum sapien. Pellentesque sit amet ex ipsum. Integer suscipit eros nec nunc facilisis, quis bibendum ipsum tincidunt.

            Ut blandit facilisis neque id venenatis. Aenean et dapibus dui, quis tincidunt nunc. Nam gravida enim sit amet quam mattis, vitae fermentum tortor congue. Vivamus et dolor ut velit mattis blandit ac sed risus. Nullam dignissim lobortis mi a tristique. Donec vitae nisl et mauris sodales imperdiet. Vestibulum eleifend leo at nibh fermentum aliquet.
        </p>
    </div>
</x-guest-layout>
